### ISSUE TITLE
Acess HF models locally

### ISSUE THREAD

**Issue by Rachneet** [itlackey/ipex-arc-fastchat#2]
Hi,

Could you give an example usage of using locally stored models in the container.

**Comment by itlackey** [comment]
Here are the docs docs for using the FastChat API

https://github.com/lm-sys/FastChat#api

Once you have the container running you can follow these examples to connect to the API.

If you need HF API, you can enable it in the startup.sh for now. I will add a flag for it soon.

**Comment by Rachneet** [comment]
Thanks a lot for a quick reply. I have been looking at their docs. I have another issue that when i run the container interactively, i get the following error

```
2023-09-25 19:11:35 | INFO | stdout | INFO:     127.0.0.1:50200 - "POST /worker_get_status HTTP/1.1" 404 Not Found
2023-09-25 19:11:35 | ERROR | controller | Get status fails: http://localhost:21002, <Response [404]>
2023-09-25 19:11:35 | INFO | controller | Remove stale worker: http://localhost:21002

```
And then we are in the waiting state. Do you have any idea why this may happen?

This is my docker-compose file, I am using CUDA here since that is what I need

```
version: "3.9"

services:
  llm_chat:
    build:
      context: .
    container_name: llm_chat
    volumes:
      - /home/abc/hf_models:/root/.cache/huggingface
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    ports:
      - "7860:7860"
      - "8000:8000"


```
